// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktmmhkudluesopslnmov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bW1oa3VkbHVlc29wc2xubW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Mzk5MTAsImV4cCI6MjA2NTExNTkxMH0.U_tqQP2NMW-rsf-SkoqHBAOTNjvV2CkUAqRjGZ1ldS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);